spring:
  profiles:
    active: local
  rabbitmq:
    port: ${RABBITMQ_PORT}
    username: ${RABBITMQ_USERNAME}
    password: ${RABBITMQ_PASSWORD}
  datasource:
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    generate-ddl: true
    show-sql: false

queuemusic:
  security:
    permitted: "/v1/auth/login/**"
  encryption:
    algorithme: ${QUEUEMUSIC_ENCRYPTION_ALGORITHME}
    secret: ${QUEUEMUSIC_ENCRYPTION_SECRET}
  jwt:
    secret: ${QUEUEMUSIC_JWT_SECRET}
    refresh:
      secret: ${QUEUEMUSIC_REFRESH_JWT_SECRET}
  session:
    song:
      timeout: PT5M
  rabbitmq:
    exchange: queuemusic
    autoqueue:
      routingKey: autoqueue
      queueName: autoqueue

