spring:
  profiles:
    active: local

queuemusic:
  security:
    permitted: >
  jwt:
    public-secret: ${QUEUEMUSIC_JWT_PUBLIC_SECRET}
    refresh:
      public-secret: ${QUEUEMUSIC_REFRESH_JWT_PUBLIC_SECRET}

clients:
  idp:
    spotify-facade:
      id: ${SPOTIFY_FACADE_CLIENT_ID}
      secret: ${SPOTIFY_FACADE_CLIENT_SECRET}
    session-service:
      id: ${SESSION_SERVICE_CLIENT_ID}
      secret: ${SESSION_SERVICE_CLIENT_SECRET}