spring:
  profiles:
    active: local

clients:

queuemusic:
  security:
    permitted: "/v1/auth/login/**"
  encryption:
    algorithme: ${QUEUEMUSIC_ENCRYPTION_ALGORITHME}
    secret: ${QUEUEMUSIC_ENCRYPTION_SECRET}
  jwt:
    secret: ${QUEUEMUSIC_JWT_SECRET}
    refresh:
      secret: ${QUEUEMUSIC_REFRESH_JWT_SECRET}
  session:
    song:
      timeout: PT5M

