version: '3.9'

services:
  postgresql:
    image: postgres:latest
    env_file: .env
    restart: on-failure
    volumes:
      - queuemusic_postgresql:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  rabbitmq:
    image: rabbitmq:latest
    restart: on-failure
    env_file: .env
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - queuemusic_rabbitmq:/var/lib/rabbitmq/data
      - queuemusic_rabbitmq:/var/log/rabbitmq/data

volumes:
  queuemusic_postgresql:
  queuemusic_rabbitmq: