FROM maven:latest
ARG CI_GITHUB_USERNAME
ARG CI_GITHUB_PASSWORD
ARG CI_GITHUB_REPOSITORY

ENV CI_GITHUB_USERNAME=$CI_GITHUB_USERNAME
ENV CI_GITHUB_PASSWORD=$CI_GITHUB_PASSWORD
ENV CI_GITHUB_REPOSITORY=$CI_GITHUB_REPOSITORY

WORKDIR /package
COPY . .
RUN mvn deploy -s ci-settings.xml