FROM maven:latest
ARG GITHUB_USERNAME
ARG GITHUB_PASSWORD
ARG GITHUB_REPOSITORY

ENV GITHUB_USERNAME=$GITHUB_USERNAME
ENV GITHUB_PASSWORD=$GITHUB_PASSWORD
ENV GITHUB_REPOSITORY=$GITHUB_REPOSITORY

WORKDIR /package
COPY . .
RUN mvn deploy -s ci-settings.xml