image: ghcr.io/tijsgroenendaal/autoplay-consumer
imageTag: 0.0.16
imagePullPolicy: "IfNotPresent"
name: autoplay-consumer
profile: prd
command:
  - /opt/entrypoint.sh
  - -Dspring.profiles.active=prd
extraArgs:
  - -XX:MaxRAMPercentage=70.0
  - -XX:+UseG1GC

service:
  enabled: false

deployment:
  enabled: true
  replicaCount: 2

environmentVariables:
  - name: RABBITMQ_HOST
    valueFrom:
      secretKeyRef:
        name: queuemusic-secrets
        key: RABBITMQ_HOST
  - name: RABBITMQ_PORT
    valueFrom:
      secretKeyRef:
        name: queuemusic-secrets
        key: RABBITMQ_PORT
  - name: RABBITMQ_USERNAME
    valueFrom:
      secretKeyRef:
        name: queuemusic-secrets
        key: RABBITMQ_USERNAME
  - name: RABBITMQ_PASSWORD
    valueFrom:
      secretKeyRef:
        name: queuemusic-secrets
        key: RABBITMQ_PASSWORD

  # Service Secrets
  - name: IDP_SERVICE_URL
    valueFrom:
      secretKeyRef:
        name: queuemusic-secrets
        key: IDP_SERVICE_URL
  - name: SPOTIFY_FACADE_URL
    valueFrom:
      secretKeyRef:
        name: queuemusic-secrets
        key: SPOTIFY_FACADE_URL

  - name: SPOTIFY_FACADE_CLIENT_ID
    valueFrom:
      secretKeyRef:
        name: queuemusic-secrets
        key: SPOTIFY_FACADE_CLIENT_ID

  - name: SPOTIFY_FACADE_CLIENT_SECRET
    valueFrom:
      secretKeyRef:
        name: queuemusic-secrets
        key: SPOTIFY_FACADE_CLIENT_SECRET

labels:
  app: autoplay-consumer
  chart: api-springboot
  release: latest

ingress:
  enabled: false

resources:
    requests:
        memory: "350Mi"
        cpu: "100m"
    limits:
        memory: "512Mi"
