image: ghcr.io/tijsgroenendaal/user-event-streamer
imageTag: v1.0.4
imagePullPolicy: "IfNotPresent"
name: user-event-streamer
replicaCount: 4
profile: prd
command:
  - /opt/entrypoint.sh

service:
  enabled: true
  servicePort: 80
  type: ClusterIP
port: 8080

environmentVariables:
  - name: RABBITMQ_HOST
    valueFrom:
      secretKeyRef:
        name: queuemusic-secrets
        key: RABBITMQ_HOST
  - name: RABBITMQ_PORT
    valueFrom:
      secretKeyRef:
        name: queuemusic-secrets
        key: RABBITMQ_PORT
  - name: RABBITMQ_USERNAME
    valueFrom:
      secretKeyRef:
        name: queuemusic-secrets
        key: RABBITMQ_USERNAME
  - name: RABBITMQ_PASSWORD
    valueFrom:
      secretKeyRef:
        name: queuemusic-secrets
        key: RABBITMQ_PASSWORD
labels:
  app: user-event-streamer
  chart: api-springboot
  release: latest

ingress:
  enabled: false
