apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: application-arc-systems
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - chart: gha-runner-scale-set-controller
      repoURL: 'https://tijsgroenendaal.github.io/QueueMusicService'
      targetRevision: 0.8.3
      helm:
        valueFiles:
          - $values/applications/arc-systems/values.yaml
    - repoURL: 'https://github.com/TijsGroenendaal/QueueMusicService'
      targetRevision: "k8s/argocd-apps"
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: arc-systems
  syncPolicy:
    syncOptions:
      - ServerSideApply=true
      - CreateNamespace=false
    automated:
      prune: false
      selfHeal: false
