clients:
  spotify-api: https://api.spotify.com
  account-spotify-api: https://accounts.spotify.com/api/token

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/${POSTGRES_DB}?user=${POSTGRES_USER}&password=${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      minimum-idle: 1
      maximum-pool-size: 10
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: false

queuemusic:
  jwt:
    secret: ${QUEUEMUSIC_JWT_SECRET}
    refresh:
      secret: ${QUEUEMUSIC_REFRESH_JWT_SECRET}
  spotify:
    id: ${SPOTIFY_CLIENT_ID}
    secret: ${SPOTIFY_CLIENT_SECRET}

logging:
  level:
    nl.tijsgroenendaal.queuemusicservice.clients.spotify_client.clients.SpotifyTokenClient: debug