clients:
  spotify-facade: ${SPOTIFY_FACADE_URL}

spring:
  datasource:
    url: jdbc:postgresql://${IDP_S_POSTGRES_HOST}:5432/${IDP_S_POSTGRES_DB}?user=${IDP_S_POSTGRES_USER}&password=${IDP_S_POSTGRES_PASSWORD}
    hikari:
      minimum-idle: 4
      maximum-pool-size: 16
  jpa:
    hibernate:
      ddl-auto: none
