spring:
  datasource:
    url: jdbc:postgresql://${SPOTIFY_F_POSTGRES_HOST}:5432/${SPOTIFY_F_POSTGRES_DB}?user=${SPOTIFY_F_POSTGRES_USER}&password=${SPOTIFY_F_POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      minimum-idle: 4
      maximum-pool-size: 16
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: false

server:
  port: 8081
