spring:
  profiles:
    active: local

queuemusic:
  encryption:
    algorithme: ${QUEUEMUSIC_ENCRYPTION_ALGORITHME}
    secret: ${QUEUEMUSIC_ENCRYPTION_SECRET}
  jwt:
    secret: ${QUEUEMUSIC_JWT_SECRET}
    refresh:
      secret: ${QUEUEMUSIC_REFRESH_JWT_SECRET}
  spotify:
    id: ${SPOTIFY_CLIENT_ID}
    secret: ${SPOTIFY_CLIENT_SECRET}