spring:
  profiles:
    active: local

clients:
  spotify-api: https://api.spotify.com
  account-spotify-api: https://accounts.spotify.com/api/token

queuemusic:
  security:
    permitted: "/v1/auth/login/**"
  encryption:
    algorithme: ${QUEUEMUSIC_ENCRYPTION_ALGORITHME}
    secret: ${QUEUEMUSIC_ENCRYPTION_SECRET}
  jwt:
    secret: ${QUEUEMUSIC_JWT_SECRET}
    refresh:
      secret: ${QUEUEMUSIC_REFRESH_JWT_SECRET}
  spotify:
    id: ${SPOTIFY_CLIENT_ID}
    secret: ${SPOTIFY_CLIENT_SECRET}