spring:
  profiles:
    active: local
  rabbitmq:
    port: ${RABBITMQ_PORT}
    username: ${RABBITMQ_USERNAME}
    password: ${RABBITMQ_PASSWORD}
  datasource:
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    generate-ddl: true
    show-sql: false

queuemusic:
  security:
    permitted: >
      /manage/metrics
  jwt:
    public-secret: ${QUEUEMUSIC_JWT_PUBLIC_SECRET}
    refresh:
      public-secret: ${QUEUEMUSIC_REFRESH_JWT_PUBLIC_SECRET}
  session:
    song:
      timeout: PT5M
  rabbitmq:
    autoqueue:
      exchange: queuemusic
      routingKey: autoqueue
      queueName: autoqueue
    userevent:
      exchange: user_event
