clients:
  idp-service: ${IDP_SERVICE_URL}

spring:
  rabbitmq:
    host: ${RABBITMQ_HOST}
  datasource:
    url: jdbc:postgresql://${SESSION_S_POSTGRES_HOST}:5432/${SESSION_S_POSTGRES_DB}?user=${SESSION_S_POSTGRES_USER}&password=${SESSION_S_POSTGRES_PASSWORD}
    hikari:
      minimum-idle: 4
      maximum-pool-size: 16
  jpa:
    hibernate:
      ddl-auto: none
