server:
  port: 8083

clients:
  idp-service: localhost:8082

spring:
  rabbitmq:
    host: localhost
  datasource:
    url: jdbc:postgresql://localhost:5432/${SESSION_S_POSTGRES_DB}?user=${SESSION_S_POSTGRES_USER}&password=${SESSION_S_POSTGRES_PASSWORD}
    hikari:
      minimum-idle: 1
      maximum-pool-size: 10
  jpa:
    hibernate:
      ddl-auto: update
