spring:
  profiles:
    active: local
  datasource:
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    generate-ddl: true
    show-sql: false

queuemusic:
  security:
    permitted: >
  jwt:
    public-secret: ${QUEUEMUSIC_JWT_PUBLIC_SECRET}
    refresh:
      public-secret: ${QUEUEMUSIC_REFRESH_JWT_PUBLIC_SECRET}
  session:
    song:
      timeout: PT5M