server:
  port: 8083

clients:
  idp-service: localhost:8082

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/${POSTGRES_SESSION_DB}?user=${POSTGRES_SESSION_USER}&password=${POSTGRES_SESSION_PASSWORD}
    hikari:
      minimum-idle: 1
      maximum-pool-size: 10
  jpa:
    hibernate:
      ddl-auto: update
