{{- if .Values.deployment.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}
  labels: {{ include "labels" . | indent 4 }}
  annotations:
    {{- range $key, $value := .Values.annotations }}
    {{ $key }}: {{ default "" $value | quote }}
    {{- end }}
spec:
  selector:
    matchLabels: {{ include "selector-labels" . | indent 6 }}
{{- if .Values.deployment.replicaCount }}
  replicas: {{ .Values.deployment.replicaCount }}
{{- end }}
{{- if not .Values.strategy }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
{{- else }}
  strategy:
  {{toYaml .Values.strategy | indent 6}}
  {{- end }}
  template:
    metadata:
      labels: {{ include "labels" . | indent 8 }}
      annotations:
        {{- range $key, $value := .Values.podAnnotations }}
        {{ $key }}: {{ default "" $value | quote }}
        {{- end }}
    spec:
      imagePullSecrets:
        - name: ghcr-login-secret
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
      - name: {{ .Values.name }}
        image: "{{ .Values.image }}:{{ .Values.imageTagOverride | default .Values.imageTag }}"
        imagePullPolicy: {{ .Values.imagePullPolicy }}
        ports:
          - containerPort: {{ default 80 .Values.port }}
        command:
{{- if not .Values.command }}
        - "/opt/run.sh"
        - {{ default 80 .Values.port | quote }}
        - "-Dspring.profiles.active={{ .Values.profile }}"
{{- end }}
{{- if .Values.command }}
{{ toYaml .Values.command | indent 8 }}
{{- end }}
{{- if .Values.extraArgs }}
{{ toYaml .Values.extraArgs | indent 8 }}
{{- end }}
        env:
{{- /*
  # -- start environmentVariables injection
*/}}
{{- if .Values.environmentVariables }}
{{- if typeIs "map[string]interface {}" .Values.environmentVariables }}
{{- range $key, $value := .Values.environmentVariables }}
          - name: {{ $key }}
{{ toYaml $value | indent 12 }}
{{- end }}
{{- else }}
{{ toYaml .Values.environmentVariables | indent 10 }}
{{- end }}
{{- end }}
{{- end -}}
{{- /*
# -- end environmentVariables injection
  */}}
