spring:
  profiles:
    active: local
  rabbitmq:
    port: ${RABBITMQ_PORT}
    username: ${RABBITMQ_USERNAME}
    password: ${RABBITMQ_PASSWORD}

queuemusic:
  rabbitmq:
    exchange: queuemusic
    autoqueue:
      routingKey: autoqueue
      queueName: autoqueue

clients:
  idp:
    spotify-facade:
      id: ${SPOTIFY_FACADE_CLIENT_ID}
      secret: ${SPOTIFY_FACADE_CLIENT_SECRET}