certificate:
  enabled: true
  domain: argo.tijsgroenendaal.nl

server:
  ingress:
    enabled: true
    hostname: argo.tijsgroenendaal.nl
    ingressClassName: nginx
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
      nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
      nginx.ingress.kubernetes.io/ssl-passthrough: "true"
      nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    tls: true
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
      namespace: monitoring

controller:
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
      namespace: monitoring

repoServer:
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
      namespace: monitoring

applicationSet:
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
      namespace: monitoring

dex:
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
      namespace: monitoring