image: ghcr.io/tijsgroenendaal/idp-service
imageTag: 0.0.27
imagePullPolicy: "IfNotPresent"
name: idp-service
profile: prd
command:
  - /opt/entrypoint.sh
  - -Dspring.profiles.active=prd
extraArgs:
  - -XX:MaxRAMPercentage=70.0
  - -XX:+UseG1GC

service:
  enabled: true
  servicePort: 80
  type: ClusterIP
  targetPort: 8080

servicemonitor:
  enabled: true
  interval: 30s
  scrapeTimeout: 10s
  port: 8081
  path: /manage/metrics

deployment:
  enabled: true
  replicaCount: 2

environmentVariables:
  # JWT Secrets
  - name: QUEUEMUSIC_JWT_PUBLIC_SECRET
    valueFrom:
      secretKeyRef:
        name: queuemusic-secrets
        key: QUEUEMUSIC_JWT_PUBLIC_SECRET
  - name: QUEUEMUSIC_REFRESH_JWT_PUBLIC_SECRET
    valueFrom:
      secretKeyRef:
        name: queuemusic-secrets
        key: QUEUEMUSIC_REFRESH_JWT_PUBLIC_SECRET

  - name: QUEUEMUSIC_JWT_SECRET
    valueFrom:
      secretKeyRef:
        name: queuemusic-secrets
        key: QUEUEMUSIC_JWT_SECRET
  - name: QUEUEMUSIC_REFRESH_JWT_SECRET
    valueFrom:
      secretKeyRef:
        name: queuemusic-secrets
        key: QUEUEMUSIC_REFRESH_JWT_SECRET

  # Postgres Secrets
  - name: IDP_S_POSTGRES_HOST
    valueFrom:
      secretKeyRef:
        name: queuemusic-secrets
        key: IDP_S_POSTGRES_HOST
  - name: IDP_S_POSTGRES_DB
    valueFrom:
      secretKeyRef:
        name: queuemusic-secrets
        key: IDP_S_POSTGRES_DB
  - name: IDP_S_POSTGRES_USER
    valueFrom:
      secretKeyRef:
        name: queuemusic-secrets
        key: IDP_S_POSTGRES_USER
  - name: IDP_S_POSTGRES_PASSWORD
    valueFrom:
      secretKeyRef:
        name: queuemusic-secrets
        key: IDP_S_POSTGRES_PASSWORD

  # Service Secrets
  - name: SPOTIFY_FACADE_URL
    valueFrom:
      secretKeyRef:
        name: queuemusic-secrets
        key: SPOTIFY_FACADE_URL

  - name: SPOTIFY_FACADE_CLIENT_ID
    valueFrom:
      secretKeyRef:
        name: queuemusic-secrets
        key: SPOTIFY_FACADE_CLIENT_ID

  - name: SPOTIFY_FACADE_CLIENT_SECRET
    valueFrom:
      secretKeyRef:
        name: queuemusic-secrets
        key: SPOTIFY_FACADE_CLIENT_SECRET

  - name: QUEUEMUSIC_ENCRYPTION_ALGORITHME
    valueFrom:
      secretKeyRef:
        name: queuemusic-secrets
        key: QUEUEMUSIC_ENCRYPTION_ALGORITHME

  - name: QUEUEMUSIC_ENCRYPTION_SECRET
    valueFrom:
      secretKeyRef:
        name: queuemusic-secrets
        key: QUEUEMUSIC_ENCRYPTION_SECRET

labels:
  app: idp-service
  chart: api-springboot
  release: latest

ingress:
  enabled: true
  hosts:
    - k8s.tijsgroenendaal.nl
  path: /idp(/|$)(.*)
  annotations:
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: "true"
    ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
  tls:
    - secretName: idp-service-tijsgroenendaal-nl
      hosts:
        - k8s.tijsgroenendaal.nl

resources:
  requests:
    memory: "350Mi"
    cpu: "100m"
  limits:
    memory: "512Mi"
    