image: ghcr.io/tijsgroenendaal/idp-service
imageTag: 0.0.15
imagePullPolicy: "IfNotPresent"
name: idp-service
replicaCount: 1
profile: prd
command:
  - /opt/entrypoint.sh
  - -Dspring.profiles.active=prd

service:
  enabled: true
  servicePort: 80
  type: ClusterIP
port: 8080

environmentVariables:
  # JWT Secrets
  - name: QUEUEMUSIC_JWT_PUBLIC_SECRET
    valueFrom:
      secretKeyRef:
        name: queuemusic-secrets
        key: QUEUEMUSIC_JWT_PUBLIC_SECRET
  - name: QUEUEMUSIC_REFRESH_JWT_PUBLIC_SECRET
    valueFrom:
      secretKeyRef:
        name: queuemusic-secrets
        key: QUEUEMUSIC_REFRESH_JWT_PUBLIC_SECRET

  - name: QUEUEMUSIC_JWT_SECRET
    valueFrom:
      secretKeyRef:
        name: queuemusic-secrets
        key: QUEUEMUSIC_JWT_SECRET
  - name: QUEUEMUSIC_REFRESH_JWT_SECRET
    valueFrom:
      secretKeyRef:
        name: queuemusic-secrets
        key: QUEUEMUSIC_REFRESH_JWT_SECRET

  # Postgres Secrets
  - name: IDP_S_POSTGRES_HOST
    valueFrom:
      secretKeyRef:
        name: queuemusic-secrets
        key: IDP_S_POSTGRES_HOST
  - name: IDP_S_POSTGRES_DB
    valueFrom:
      secretKeyRef:
        name: queuemusic-secrets
        key: IDP_S_POSTGRES_DB
  - name: IDP_S_POSTGRES_USER
    valueFrom:
      secretKeyRef:
        name: queuemusic-secrets
        key: IDP_S_POSTGRES_USER
  - name: IDP_S_POSTGRES_PASSWORD
    valueFrom:
      secretKeyRef:
        name: queuemusic-secrets
        key: IDP_S_POSTGRES_PASSWORD

  # Service Secrets
  - name: SPOTIFY_FACADE_URL
    valueFrom:
      secretKeyRef:
        name: queuemusic-secrets
        key: SPOTIFY_FACADE_URL

  - name: SPOTIFY_FACADE_CLIENT_ID
    valueFrom:
      secretKeyRef:
        name: queuemusic-secrets
        key: SPOTIFY_FACADE_CLIENT_ID

  - name: SPOTIFY_FACADE_CLIENT_SECRET
    valueFrom:
      secretKeyRef:
        name: queuemusic-secrets
        key: SPOTIFY_FACADE_CLIENT_SECRET

  - name: QUEUEMUSIC_ENCRYPTION_ALGORITHME
    valueFrom:
      secretKeyRef:
        name: queuemusic-secrets
        key: QUEUEMUSIC_ENCRYPTION_ALGORITHME

  - name: QUEUEMUSIC_ENCRYPTION_SECRET
    valueFrom:
      secretKeyRef:
        name: queuemusic-secrets
        key: QUEUEMUSIC_ENCRYPTION_SECRET

labels:
  app: idp-service
  chart: api-springboot
  release: latest

ingress:
  enabled: true
  hosts:
    - k8s.tijsgroenendaal.nl
  path: /idp
  annotations:
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: "true"
    ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
  tls:
    - secretName: idp-service-tijsgroenendaal-nl
      hosts:
        - k8s.tijsgroenendaal.nl