apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rabbitmq
  namespace: argocd
spec:
  project: default
  sources:
    - chart: rabbitmq
      repoURL: 'https://charts.bitnami.com/bitnami'
      targetRevision: 14.6.5
      helm:
        valueFiles:
          - $values/applications/rabbitmq/values.yaml
    - repoURL: 'https://github.com/TijsGroenendaal/QueueMusicService'
      targetRevision: "k8s/argocd-apps"
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: rabbitmq
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: false
      selfHeal: false
