apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus-stack
  namespace: argocd
spec:
  project: default
  sources:
    - chart: kube-prometheus-stack
      repoURL: 'https://prometheus-community.github.io/helm-charts'
      targetRevision: 57.2.0
      helm:
        valueFiles:
          - $values/applications/prometheus-stack/values.yaml
    - repoURL: 'https://github.com/TijsGroenendaal/QueueMusicService'
      targetRevision: "k8s/argocd-apps"
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: false
      selfHeal: false
