crds:
  enabled: false

grafana:
  ingress:
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
    enabled: true
    hosts:
      - grafana.tijsgroenendaal.nl
    tls:
      - secretName: grafana-secret-tls
        hosts:
          - grafana.tijsgroenendaal.nl

  persistence:
    enabled: true
    type: sts
    storageClassName: "local-storage"
    accessModes:
      - ReadWriteOnce
    size: 5Gi
    finalizers:
      - kubernetes.io/pvc-protection

prometheus:
  prometheusSpec:
    secrets: ['etcd-client-cert']
    serviceMonitorSelectorNilUsesHelmValues: false
    storage:
      volumeClaimTemplate:
        spec:
          storageClassName: local-storage
          resources:
            requests:
              storage: 10Gi

kubeEtcd:
  serviceMonitor:
    scheme: https
    insecureSkipVerify: false
    serverName: localhost
    caFile: /etc/prometheus/secrets/etcd-client-cert/ca.crt
    certFile: /etc/prometheus/secrets/etcd-client-cert/healthcheck-client.crt
    keyFile: /etc/prometheus/secrets/etcd-client-cert/healthcheck-client.key
