image: ghcr.io/tijsgroenendaal/spotify-facade
imageTag: 0.0.23
imagePullPolicy: "IfNotPresent"
name: spotify-facade
profile: prd
command:
  - /opt/entrypoint.sh
  - -Dspring.profiles.active=prd
extraArgs:
  - -XX:MaxRAMPercentage=70.0
  - -XX:+UseG1GC
  - -XX:InitialRAMPercentage=70.0

service:
  enabled: true
  servicePort: 80
  type: ClusterIP
  targetPort: 8080

deployment:
  enabled: true
  replicaCount: 2

environmentVariables:
  # JWT Secrets
  - name: QUEUEMUSIC_JWT_PUBLIC_SECRET
    valueFrom:
      secretKeyRef:
        name: queuemusic-secrets
        key: QUEUEMUSIC_JWT_PUBLIC_SECRET
  - name: QUEUEMUSIC_REFRESH_JWT_PUBLIC_SECRET
    valueFrom:
      secretKeyRef:
        name: queuemusic-secrets
        key: QUEUEMUSIC_REFRESH_JWT_PUBLIC_SECRET

  # Postgres Secrets
  - name: SPOTIFY_F_POSTGRES_HOST
    valueFrom:
      secretKeyRef:
        name: queuemusic-secrets
        key: SPOTIFY_F_POSTGRES_HOST
  - name: SPOTIFY_F_POSTGRES_DB
    valueFrom:
      secretKeyRef:
        name: queuemusic-secrets
        key: SPOTIFY_F_POSTGRES_DB
  - name: SPOTIFY_F_POSTGRES_USER
    valueFrom:
      secretKeyRef:
        name: queuemusic-secrets
        key: SPOTIFY_F_POSTGRES_USER
  - name: SPOTIFY_F_POSTGRES_PASSWORD
    valueFrom:
      secretKeyRef:
        name: queuemusic-secrets
        key: SPOTIFY_F_POSTGRES_PASSWORD

  # Service Secrets
  - name: SPOTIFY_CLIENT_ID
    valueFrom:
      secretKeyRef:
        name: queuemusic-secrets
        key: SPOTIFY_CLIENT_ID

  - name: SPOTIFY_CLIENT_SECRET
    valueFrom:
      secretKeyRef:
        name: queuemusic-secrets
        key: SPOTIFY_CLIENT_SECRET

  - name: QUEUEMUSIC_ENCRYPTION_ALGORITHME
    valueFrom:
      secretKeyRef:
        name: queuemusic-secrets
        key: QUEUEMUSIC_ENCRYPTION_ALGORITHME

  - name: QUEUEMUSIC_ENCRYPTION_SECRET
    valueFrom:
      secretKeyRef:
        name: queuemusic-secrets
        key: QUEUEMUSIC_ENCRYPTION_SECRET
labels:
  app: spotify-facade
  chart: api-springboot
  release: latest

ingress:
  enabled: false
