image: ghcr.io/tijsgroenendaal/session-service
imageTag: 0.0.9
imagePullPolicy: "IfNotPresent"
name: session-service
replicaCount: 1
profile: prd
command:
  - /opt/entrypoint.sh
  - -Dspring.profiles.active=prd
extraArgs:
  - -XX:MaxRAMPercentage=70.0
  - -XX:+UseG1GC

service:
  enabled: true
  servicePort: 80
  type: ClusterIP
port: 8080

environmentVariables:
  - name: RABBITMQ_HOST
    valueFrom:
      secretKeyRef:
        name: queuemusic-secrets
        key: RABBITMQ_HOST
  - name: RABBITMQ_PORT
    valueFrom:
      secretKeyRef:
        name: queuemusic-secrets
        key: RABBITMQ_PORT
  - name: RABBITMQ_USERNAME
    valueFrom:
      secretKeyRef:
        name: queuemusic-secrets
        key: RABBITMQ_USERNAME
  - name: RABBITMQ_PASSWORD
    valueFrom:
      secretKeyRef:
        name: queuemusic-secrets
        key: RABBITMQ_PASSWORD

  # JWT Secrets
  - name: QUEUEMUSIC_JWT_PUBLIC_SECRET
    valueFrom:
      secretKeyRef:
        name: queuemusic-secrets
        key: QUEUEMUSIC_JWT_PUBLIC_SECRET
  - name: QUEUEMUSIC_REFRESH_JWT_PUBLIC_SECRET
    valueFrom:
      secretKeyRef:
        name: queuemusic-secrets
        key: QUEUEMUSIC_REFRESH_JWT_PUBLIC_SECRET

  # Postgres Secrets
  - name: SESSION_S_POSTGRES_HOST
    valueFrom:
      secretKeyRef:
        name: queuemusic-secrets
        key: SESSION_S_POSTGRES_HOST
  - name: SESSION_S_POSTGRES_DB
    valueFrom:
      secretKeyRef:
        name: queuemusic-secrets
        key: SESSION_S_POSTGRES_DB
  - name: SESSION_S_POSTGRES_USER
    valueFrom:
      secretKeyRef:
        name: queuemusic-secrets
        key: SESSION_S_POSTGRES_USER
  - name: SESSION_S_POSTGRES_PASSWORD
    valueFrom:
      secretKeyRef:
        name: queuemusic-secrets
        key: SESSION_S_POSTGRES_PASSWORD
labels:
  app: session-service
  chart: api-springboot
  release: latest

ingress:
  enabled: false

resources:
  limits:
    memory: 500mi
  requests:
    memory: 150mi