githubConfigUrl: https://github.com/TijsGroenendaal/QueueMusicService

githubConfigSecret: arc-github

minRunners: 2
maxRunners: 6

containerMode:
  type: "kubernetes"
  kubernetesModeWorkVolumeClaim:
      accessModes: ["ReadWriteOnce"]
      storageClassName: "local-storage"
      resources:
        requests:
          storage: 1Gi

template:
  spec:
    securityContext:
      fsGroup: 1001

controllerServiceAccount:
   namespace: arc-systems
   name: application-arc-systems-gha-rs-controller