githubConfigUrl: https://github.com/TijsGroenendaal/QueueMusicService

githubConfigSecret: arc-github

minRunners: 2
maxRunners: 6

template:
  spec:
    securityContext:
      privileged: true
    containers:
      - name: runner
        image: ghcr.io/actions/actions-runner:latest
        command: [ "/home/runner/run.sh" ]
        env:
          - name: ACTIONS_RUNNER_CONTAINER_HOOKS
            value: /home/runner/k8s/index.js
          - name: ACTIONS_RUNNER_POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: ACTIONS_RUNNER_REQUIRE_JOB_CONTAINER
            value: "false"

controllerServiceAccount:
   namespace: arc-systems
   name: application-arc-systems-gha-rs-controller