name: Github Release

on:
  workflow_call:
    inputs:
      tag:
        description: "Tag of the release"
        required: true
        type: string

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: softprops/action-gh-release@v1
        with:
          tag_name: "${{ inputs.tag }}"
          name: "${{ inputs.tag }}"