on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
    paths:
      - './QueueMusicFacade/**'

jobs:
  test:
    name: 'Test QueueMusicFacade Package'
    runs-on: ubuntu-latest
    env:
      CI_GITHUB_PASSWORD: ${{ secrets.CI_GITHUB_PASSWORD }}
      CI_GITHUB_USERNAME: ${{ secrets.CI_GITHUB_USERNAME }}
      CI_GITHUB_REPOSITORY: ${{ secrets.CI_GITHUB_REPOSITORY }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: maven
      - name: 'Test QueueMusicFacade'
        working-directory: ./QueueMusicFacade
        run: mvn --batch-mode --update-snapshots test -s ci-settings.xml

  release:
    name: 'Release QueueMusicFacade Container'
    runs-on: ubuntu-latest
    env:
      CI_GITHUB_PASSWORD: ${{ secrets.CI_GITHUB_PASSWORD }}
      CI_GITHUB_USERNAME: ${{ secrets.CI_GITHUB_USERNAME }}
      CI_GITHUB_REPOSITORY: ${{ secrets.CI_GITHUB_REPOSITORY }}
      IMAGE_NAME: queuemusic-facade
    if: ${{ github.ref == 'refs/heads/main' }}
    needs:
      - test
    steps:
      - uses: actions/checkout@v2
      - name: 'Login Github Container Registry'
        run: echo $CI_GITHUB_PASSWORD | docker login ghcr.io -u $CI_GITHUB_USERNAME --password-stdin
      - name: 'Release QueueMusicFacade Container'
        working-directory: ./QueueMusicFacade
        run: |
          SHORT_SHA=${GITHUB_SHA:0:8}
          IMAGE_TAG=$(echo "ghcr.io/$CI_GITHUB_USERNAME/$IMAGE_NAME:$SHORT_SHA" | tr '[:upper:]' '[:lower:]')
          docker build --build-arg CI_GITHUB_USERNAME=${{ env.CI_GITHUB_USERNAME }} --build-arg CI_GITHUB_PASSWORD=${{ env.CI_GITHUB_PASSWORD }} --build-arg CI_GITHUB_REPOSITORY=${{ env.CI_GITHUB_REPOSITORY }} -t $IMAGE_TAG .
