on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
    paths:
      - 'QuMuSecurity/**'

jobs:
  test:
    name: 'Test QuMuSecurity Package'
    runs-on: ubuntu-latest
    env:
      CI_GITHUB_PASSWORD: ${{ secrets.CI_GITHUB_PASSWORD }}
      CI_GITHUB_USERNAME: ${{ secrets.CI_GITHUB_USERNAME }}
      CI_GITHUB_REPOSITORY: ${{ secrets.CI_GITHUB_REPOSITORY }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: maven
      - name: 'Test QuMuSecurity'
        working-directory: ./QuMuSecurity
        run: mvn --batch-mode --update-snapshots test -s ci-settings.xml

  release:
    name: 'Release QuMuSecurity Package'
    runs-on: ubuntu-latest
    env:
      CI_GITHUB_PASSWORD: ${{ secrets.CI_GITHUB_PASSWORD }}
      CI_GITHUB_USERNAME: ${{ secrets.CI_GITHUB_USERNAME }}
      CI_GITHUB_REPOSITORY: ${{ secrets.CI_GITHUB_REPOSITORY }}
    if: ${{ github.ref == 'refs/heads/main' }}
    needs:
      - test
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v2
      - run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git pull
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: maven
      - name: 'Increment Package Version'
        working-directory: ./QuMuSecurity
        run: |
          OLD_VERSION=$(mvn org.apache.maven.plugins:maven-help-plugin:3.2.0:evaluate -Dexpression=project.version -q -DforceStdout)
          NEW_VERSION=$(echo ${OLD_VERSION} |  awk -F'.' '{print $1"."$2"."$3+1}' |  sed s/[.]$//)
          echo "NEW_VERSION=$NEW_VERSION" >> $GITHUB_ENV
          mvn versions:set -DnewVersion=$NEW_VERSION -DprocessFromLocalAggregationRoot=false -DgenerateBackupPoms=false
      - name: 'Release QuMuSecurity Package'
        working-directory: ./QuMuSecurity
        run: mvn --batch-mode --update-snapshots deploy -s ci-settings.xml -Dmaven.test.skip
      - name: 'Commit Version Update'
        run: |
          git commit -am "Increment QuMuSecurity to version $NEW_VERSION [skip ci]"
          git pull
          git push 
