on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
    paths:
      - './QuMu/**'

jobs:
  verify:
    name: 'Verify QuMu Package'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 16
        uses: actions/setup-java@v2
        with:
          java-version: '16'
          distribution: 'adopt'
          cache: maven
      - name: 'Verify QuMu'
        working-directory: ./QuMu
        run: mvn --batch-mode --update-snapshots verify -Dmaven.test.skip -s ci-settings.xml

  test:
    name: 'Test QuMu Package'
    runs-on: ubuntu-latest
    needs:
      - verify
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 16
        uses: actions/setup-java@v2
        with:
          java-version: '16'
          distribution: 'adopt'
          cache: maven
      - name: 'Test QuMu'
        working-directory: ./QuMu
        run: mvn --batch-mode --update-snapshots test -s ci-settings.xml

  release:
    name: 'Release QuMu Package'
    runs-on: ubuntu-latest
    needs:
      - test
    if: ${{ github.ref == 'refs/heads/main' }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 16
        uses: actions/setup-java@v2
        with:
          java-version: '16'
          distribution: 'adopt'
          cache: maven
      - name: 'Test QuMu'
        working-directory: ./QuMu
        run: mvn --batch-mode --update-snapshots deploy -s ci-settings.xml
