name: Release UserEventStreamer

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
    paths:
      - 'UserEventStreamer/**'

jobs:
  release:
    name: 'Release UserEventStreamer Container'
    runs-on: ubuntu-latest
    env:
      CI_GITHUB_PASSWORD: ${{ secrets.CI_GITHUB_PASSWORD }}
      CI_GITHUB_USERNAME: ${{ secrets.CI_GITHUB_USERNAME }}
      IMAGE_NAME: user-event-streamer
    if: ${{ github.ref == 'refs/heads/main' }}
    needs:
      - test
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v2
      - run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git pull
      - name: 'Login Github Container Registry'
        run: echo $CI_GITHUB_PASSWORD | docker login ghcr.io -u $CI_GITHUB_USERNAME --password-stdin
      - name: 'Increment Package Version'
        working-directory: ./UserEventStreamer
        run: |
          NEW_VERSION=$(npm version patch)
          echo "NEW_VERSION=$NEW_VERSION" >> $GITHUB_ENV
      - name: 'Release UserEventStreamer Container'
        working-directory: ./UserEventStreamer
        run: |
          IMAGE_TAG=$(echo "ghcr.io/$CI_GITHUB_USERNAME/$IMAGE_NAME:$NEW_VERSION" | tr '[:upper:]' '[:lower:]')
          docker build -t $IMAGE_TAG .
          docker push $IMAGE_TAG
      - name: 'Commit Version Update'
        run: |
          git commit -am "Increment UserEventStreamer to version $NEW_VERSION [skip ci]"
          git pull --rebase
          git push 
